ALTER TABLE user
MODIFY id VARCHAR(36),
MODIFY username VARCHAR(50),
MODIFY email VARCHAR(255),
MODIFY password VARCHAR(64);


CREATE TABLE user(
    id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL
);
